version: "3"
services:
  express:
    container_name: express-container
    restart: always
    build:
      context: ./backend
    ports: 
      - "3000:3000" 
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    links:
      - mongo
  mongo:
    container_name: mongo
    build:
      context: ./database
    ports:
      - "27017:27017"
    logging: 
      driver: none
    volumes:
      - ./mongodb:/data/db/
  angular:
    container_name: angular-container
    restart: always
    build:
      context: ./frontend
    ports: 
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules